export const adminData = {
  totalUsers: 1247,
  totalLawyers: 89,
  totalBookings: 3456,
  monthlyRevenue: 45670,
  platformCommission: 6850,
  recentTransactions: [
    {
      id: "pay1",
      bookingId: "book1",
      clientId: "client1",
      lawyerId: "lawyer1",
      amount: 200,
      platformFee: 30,
      lawyerEarnings: 170,
      status: "completed",
      paymentMethod: "card",
      transactionId: "txn_123",
      createdAt: "2025-08-01T10:00:00Z",
      completedAt: "2025-08-01T10:01:00Z",
    },
    {
      id: "pay2",
      bookingId: "book2",
      clientId: "client2",
      lawyerId: "lawyer2",
      amount: 300,
      platformFee: 45,
      lawyerEarnings: 255,
      status: "pending",
      paymentMethod: "bank",
      transactionId: "txn_124",
      createdAt: "2025-08-02T09:00:00Z",
    },
  ],
  topLawyers: [
    {
      id: "lawyer1",
      name: "Sarah Johnson",
      title: "Family Law Attorney",
      image: "user.png",
      rating: 4.9,
      reviewCount: 127,
      experience: 12,
      location: "New York, NY",
      practiceAreas: ["Family Law", "Divorce"],
      bio: "Experienced family law attorney",
      education: ["Harvard Law School"],
      languages: ["English", "Spanish"],
      hourlyRate: 200,
      availability: "Available",
      verified: true,
    },
  ],
  userGrowth: [
    { month: "Jan", users: 850 },
    { month: "Feb", users: 920 },
    { month: "Mar", users: 1050 },
    { month: "Apr", users: 1150 },
    { month: "May", users: 1200 },
    { month: "Jun", users: 1247 },
  ],
};

export const revenueData = [
  { month: "Jan", revenue: 32000, commission: 4800 },
  { month: "Feb", revenue: 38000, commission: 5700 },
  { month: "Mar", revenue: 42000, commission: 6300 },
  { month: "Apr", revenue: 39000, commission: 5850 },
  { month: "May", revenue: 45000, commission: 6750 },
  { month: "Jun", revenue: 45670, commission: 6850 },
];

export const bookingStatusData = [
  { name: "Completed", value: 2100, color: "#10B981" },
  { name: "Confirmed", value: 890, color: "#3B82F6" },
  { name: "Pending", value: 356, color: "#F59E0B" },
  { name: "Cancelled", value: 110, color: "#EF4444" },
];

export const practiceAreasData = [
  { area: "Family Law", bookings: 1200 },
  { area: "Corporate Law", bookings: 890 },
  { area: "Criminal Law", bookings: 650 },
  { area: "Real Estate", bookings: 456 },
  { area: "Immigration", bookings: 260 },
];

export const mockUsers = [
  {
    id: "1",
    name: "John Smith",
    email: "john@example.com",
    type: "client",
    joinDate: "2025-01-15",
    status: "active",
  },
  {
    id: "2",
    name: "Jane Doe",
    email: "jane@example.com",
    type: "client",
    joinDate: "2025-02-20",
    status: "active",
  },
  {
    id: "3",
    name: "Mike Johnson",
    email: "mike@example.com",
    type: "client",
    joinDate: "2025-03-10",
    status: "suspended",
  },
];

export const legalAreas = [
  {
    id: "family",
    name: "Family Law",
    description: "Divorce, custody, adoption, and family matters",
    icon: "fas fa-heart",
  },
  {
    id: "criminal",
    name: "Criminal Law",
    description: "Criminal defense and prosecution matters",
    icon: "fas fa-gavel",
  },
  {
    id: "civil",
    name: "Civil Law",
    description: "Personal injury, contracts, and civil disputes",
    icon: "fas fa-handshake",
  },
  {
    id: "corporate",
    name: "Corporate Law",
    description: "Business formation, contracts, and corporate matters",
    icon: "fas fa-building",
  },
  {
    id: "real-estate",
    name: "Real Estate",
    description: "Property transactions and real estate law",
    icon: "fas fa-home",
  },
  {
    id: "immigration",
    name: "Immigration",
    description: "Visa applications and immigration matters",
    icon: "fas fa-globe",
  },
];

export const mockLawyers = [
  {
    id: "1",
    name: "Sarah Johnson",
    title: "Family Law Attorney",
    image:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=580&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    rating: 4.9,
    reviewCount: 127,
    experience: 12,
    location: "New York, NY",
    practiceAreas: ["Family Law", "Divorce", "Child Custody"],
    bio: "Experienced family law attorney with over 12 years of practice. Specializes in divorce proceedings, child custody cases, and adoption matters.",
    education: ["Harvard Law School - JD", "Columbia University - BA"],
    languages: ["English", "Spanish"],
    hourlyRate: 350,
    availability: "Available",
    verified: true,
  },
  {
    id: "2",
    name: "Michael Chen",
    title: "Corporate Law Attorney",
    image:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 89,
    experience: 8,
    location: "San Francisco, CA",
    practiceAreas: ["Corporate Law", "Business Formation", "Contracts"],
    bio: "Corporate attorney helping startups and established businesses with legal matters. Expert in business formation and contract negotiations.",
    education: ["Stanford Law School - JD", "UC Berkeley - MBA"],
    languages: ["English", "Mandarin"],
    hourlyRate: 425,
    availability: "Available",
    verified: true,
  },
  {
    id: "3",
    name: "Emily Rodriguez",
    title: "Criminal Defense Attorney",
    image:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 156,
    experience: 15,
    location: "Miami, FL",
    practiceAreas: ["Criminal Defense", "DUI Defense", "White Collar Crime"],
    bio: "Aggressive criminal defense attorney with a track record of successful case outcomes. Experienced in all areas of criminal law.",
    education: [
      "University of Miami Law - JD",
      "Florida State University - BA",
    ],
    languages: ["English", "Spanish"],
    hourlyRate: 300,
    availability: "Busy",
    verified: true,
  },
  {
    id: "4",
    name: "David Thompson",
    title: "Personal Injury Attorney",
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 203,
    experience: 20,
    location: "Chicago, IL",
    practiceAreas: [
      "Personal Injury",
      "Medical Malpractice",
      "Workers Compensation",
    ],
    bio: "Dedicated personal injury attorney fighting for clients' rights. Specializes in complex personal injury and medical malpractice cases.",
    education: ["Northwestern Law - JD", "University of Illinois - BA"],
    languages: ["English"],
    hourlyRate: 275,
    availability: "Available",
    verified: true,
  },
  {
    id: "5",
    name: "Lisa Patel",
    title: "Immigration Law Attorney",
    image:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 95,
    experience: 10,
    location: "Houston, TX",
    practiceAreas: [
      "Immigration Law",
      "Visa Applications",
      "Deportation Defense",
    ],
    bio: "Expert in immigration law, assisting with visas, green cards, and deportation cases. Committed to client success.",
    education: ["Yale Law School - JD", "University of Texas - BA"],
    languages: ["English", "Hindi"],
    hourlyRate: 320,
    availability: "Available",
    verified: true,
  },
  {
    id: "6",
    name: "Robert Kim",
    title: "Intellectual Property Attorney",
    image:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 110,
    experience: 14,
    location: "Seattle, WA",
    practiceAreas: ["Intellectual Property", "Trademarks", "Patents"],
    bio: "Specializes in protecting intellectual property for businesses and individuals. Experienced in trademarks and patent law.",
    education: ["UCLA Law - JD", "University of Washington - BS"],
    languages: ["English", "Korean"],
    hourlyRate: 450,
    availability: "Busy",
    verified: true,
  },
  {
    id: "7",
    name: "Jennifer Lee",
    title: "Employment Law Attorney",
    image:
      "https://images.unsplash.com/photo-1499952127939-9bbf5af6c51c?w=400&h=400&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 75,
    experience: 9,
    location: "Los Angeles, CA",
    practiceAreas: ["Employment Law", "Discrimination", "Wage Disputes"],
    bio: "Advocates for employees in workplace disputes. Expertise in discrimination and wage-related cases.",
    education: ["USC Gould School of Law - JD", "UCLA - BA"],
    languages: ["English", "Chinese"],
    hourlyRate: 375,
    availability: "Available",
    verified: true,
  },
  {
    id: "8",
    name: "Thomas Garcia",
    title: "Real Estate Attorney",
    image:
      "https://images.unsplash.com/photo-1502685104226-ee32379fefbe?w=400&h=400&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 132,
    experience: 16,
    location: "Phoenix, AZ",
    practiceAreas: ["Real Estate", "Property Disputes", "Leases"],
    bio: "Handles real estate transactions and disputes with over 16 years of experience.",
    education: ["Arizona State University Law - JD", "ASU - BS"],
    languages: ["English", "Spanish"],
    hourlyRate: 400,
    availability: "Available",
    verified: true,
  },
  {
    id: "9",
    name: "Amanda Brown",
    title: "Estate Planning Attorney",
    image:
      "https://images.unsplash.com/photo-1503467914188-9d7e9b8e4b8e?w=400&h=400&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 88,
    experience: 11,
    location: "Boston, MA",
    practiceAreas: ["Estate Planning", "Wills", "Trusts"],
    bio: "Specializes in estate planning, wills, and trusts to secure clients' legacies.",
    education: ["Boston University Law - JD", "Harvard - BA"],
    languages: ["English"],
    hourlyRate: 325,
    availability: "Busy",
    verified: true,
  },
  {
    id: "10",
    name: "James Nguyen",
    title: "Tax Law Attorney",
    image:
      "https://images.unsplash.com/photo-1519244703995-f4e0f30006d5?w=400&h=400&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 105,
    experience: 13,
    location: "Austin, TX",
    practiceAreas: ["Tax Law", "Tax Disputes", "IRS Representation"],
    bio: "Expert in tax law, assisting with disputes and IRS representation.",
    education: ["UT Austin Law - JD", "UT Austin - BBA"],
    languages: ["English", "Vietnamese"],
    hourlyRate: 475,
    availability: "Available",
    verified: true,
  },
  {
    id: "11",
    name: "Rachel Kim",
    title: "Bankruptcy Attorney",
    image:
      "https://images.unsplash.com/photo-1531123897727-8f054bfc241f?w=400&h=400&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 70,
    experience: 7,
    location: "Denver, CO",
    practiceAreas: ["Bankruptcy", "Debt Relief", "Foreclosure Defense"],
    bio: "Helps clients navigate bankruptcy and debt relief with a compassionate approach.",
    education: ["University of Colorado Law - JD", "CU Boulder - BA"],
    languages: ["English", "Korean"],
    hourlyRate: 300,
    availability: "Available",
    verified: true,
  },
  {
    id: "12",
    name: "Carlos Ruiz",
    title: "Environmental Law Attorney",
    image:
      "https://images.unsplash.com/photo-1503104834685-8b7a3dd817f6?w=400&h=400&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 95,
    experience: 10,
    location: "Portland, OR",
    practiceAreas: ["Environmental Law", "Land Use", "Compliance"],
    bio: "Dedicated to environmental law and land use compliance.",
    education: ["Lewis & Clark Law - JD", "University of Oregon - BS"],
    languages: ["English", "Spanish"],
    hourlyRate: 375,
    availability: "Busy",
    verified: true,
  },
  {
    id: "13",
    name: "Sophie Martin",
    title: "Civil Litigation Attorney",
    image:
      "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=400&h=400&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 120,
    experience: 14,
    location: "Atlanta, GA",
    practiceAreas: ["Civil Litigation", "Contracts", "Disputes"],
    bio: "Experienced in civil litigation and contract disputes.",
    education: ["Emory University Law - JD", "UGA - BA"],
    languages: ["English", "French"],
    hourlyRate: 400,
    availability: "Available",
    verified: true,
  },
  {
    id: "14",
    name: "Daniel Patel",
    title: "Health Law Attorney",
    image:
      "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=400&h=400&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 85,
    experience: 11,
    location: "Philadelphia, PA",
    practiceAreas: ["Health Law", "HIPAA Compliance", "Medical Contracts"],
    bio: "Specializes in health law and HIPAA compliance for healthcare providers.",
    education: ["Penn Law - JD", "University of Pennsylvania - BS"],
    languages: ["English", "Hindi"],
    hourlyRate: 450,
    availability: "Busy",
    verified: true,
  },
  {
    id: "15",
    name: "Laura Singh",
    title: "Entertainment Law Attorney",
    image:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 60,
    experience: 6,
    location: "Nashville, TN",
    practiceAreas: ["Entertainment Law", "Music Contracts", "Film"],
    bio: "Represents artists and producers in entertainment law matters.",
    education: ["Vanderbilt Law - JD", "Belmont University - BA"],
    languages: ["English"],
    hourlyRate: 325,
    availability: "Available",
    verified: true,
  },
  {
    id: "16",
    name: "Matthew O’Connor",
    title: "Maritime Law Attorney",
    image:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 100,
    experience: 18,
    location: "New Orleans, LA",
    practiceAreas: ["Maritime Law", "Shipping", "Admiralty"],
    bio: "Expert in maritime law with extensive experience in shipping disputes.",
    education: ["Tulane Law - JD", "LSU - BS"],
    languages: ["English"],
    hourlyRate: 500,
    availability: "Busy",
    verified: true,
  },
  {
    id: "17",
    name: "Nicole Wong",
    title: "Cybersecurity Law Attorney",
    image:
      "https://images.unsplash.com/photo-1529626455594-4ff0802cf91f?w=400&h=400&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 80,
    experience: 9,
    location: "Portland, OR",
    practiceAreas: ["Cybersecurity Law", "Data Privacy", "Compliance"],
    bio: "Focuses on cybersecurity and data privacy law for tech companies.",
    education: ["Oregon Law - JD", "OSU - BS"],
    languages: ["English", "Cantonese"],
    hourlyRate: 400,
    availability: "Available",
    verified: true,
  },
  {
    id: "18",
    name: "Brian Lopez",
    title: "Education Law Attorney",
    image:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 65,
    experience: 8,
    location: "Raleigh, NC",
    practiceAreas: ["Education Law", "Special Education", "Title IX"],
    bio: "Advocates for students and educators in education law cases.",
    education: ["UNC Law - JD", "NC State - BA"],
    languages: ["English", "Spanish"],
    hourlyRate: 300,
    availability: "Busy",
    verified: true,
  },
  {
    id: "19",
    name: "Kelly Nguyen",
    title: "Construction Law Attorney",
    image:
      "https://images.unsplash.com/photo-1506863530036-1efeddceb993?w=400&h=400&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 110,
    experience: 13,
    location: "Dallas, TX",
    practiceAreas: ["Construction Law", "Contracts", "Disputes"],
    bio: "Handles construction law and contract disputes with expertise.",
    education: ["SMU Dedman Law - JD", "UT Dallas - BS"],
    languages: ["English", "Vietnamese"],
    hourlyRate: 375,
    availability: "Available",
    verified: true,
  },
  {
    id: "20",
    name: "Andrew Carter",
    title: "Sports Law Attorney",
    image:
      "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 90,
    experience: 10,
    location: "Orlando, FL",
    practiceAreas: ["Sports Law", "Contracts", "Endorsements"],
    bio: "Represents athletes and sports organizations in legal matters.",
    education: ["Florida Law - JD", "UCF - BA"],
    languages: ["English"],
    hourlyRate: 425,
    availability: "Busy",
    verified: true,
  },
];

export const mockReviews = [
  {
    id: "1",
    clientName: "John D.",
    rating: 5,
    comment:
      "Sarah was incredibly professional and helped me through a difficult divorce. Highly recommended!",
    date: "2024-01-15",
    lawyerId: "1",
  },
  {
    id: "2",
    clientName: "Maria S.",
    rating: 5,
    comment:
      "Michael helped us set up our startup. His expertise in corporate law is outstanding.",
    date: "2024-01-10",
    lawyerId: "2",
  },
  {
    id: "3",
    clientName: "Robert K.",
    rating: 4,
    comment:
      "Emily successfully defended my case. Great communication throughout the process.",
    date: "2024-01-08",
    lawyerId: "3",
  },
  {
    id: "4",
    clientName: "Linda T.",
    rating: 4.5,
    comment:
      "David was thorough and supportive during my personal injury claim. Highly skilled!",
    date: "2024-02-20",
    lawyerId: "4",
  },
  {
    id: "5",
    clientName: "Ahmed P.",
    rating: 4.8,
    comment:
      "Lisa provided excellent guidance on my visa application. Very knowledgeable!",
    date: "2024-03-05",
    lawyerId: "5",
  },
  {
    id: "6",
    clientName: "Sophie K.",
    rating: 5,
    comment:
      "Robert protected my trademark brilliantly. Highly recommend for IP issues!",
    date: "2024-04-12",
    lawyerId: "6",
  },
  {
    id: "7",
    clientName: "James L.",
    rating: 4.6,
    comment:
      "Jennifer resolved my employment dispute efficiently. Great service!",
    date: "2024-05-18",
    lawyerId: "7",
  },
  {
    id: "8",
    clientName: "Maria G.",
    rating: 4.7,
    comment:
      "Thomas handled my property dispute with expertise. Very satisfied!",
    date: "2024-06-25",
    lawyerId: "8",
  },
  {
    id: "9",
    clientName: "Peter B.",
    rating: 4.9,
    comment:
      "Amanda created a perfect estate plan for my family. Excellent attention to detail!",
    date: "2024-07-10",
    lawyerId: "9",
  },
  {
    id: "10",
    clientName: "Emily N.",
    rating: 5,
    comment: "James saved me from a tax audit. His knowledge is top-notch!",
    date: "2024-08-15",
    lawyerId: "10",
  },
  {
    id: "11",
    clientName: "David R.",
    rating: 4.5,
    comment:
      "Rachel guided me through bankruptcy with care. Very professional!",
    date: "2024-09-20",
    lawyerId: "11",
  },
  {
    id: "12",
    clientName: "Anna C.",
    rating: 4.7,
    comment:
      "Carlos helped with my environmental compliance issues. Great work!",
    date: "2024-10-05",
    lawyerId: "12",
  },
  {
    id: "13",
    clientName: "Mark M.",
    rating: 4.6,
    comment: "Sophie won my civil litigation case. Excellent strategy!",
    date: "2024-11-12",
    lawyerId: "13",
  },
  {
    id: "14",
    clientName: "Sarah P.",
    rating: 4.9,
    comment:
      "Daniel ensured my healthcare compliance was flawless. Highly recommend!",
    date: "2024-12-18",
    lawyerId: "14",
  },
  {
    id: "15",
    clientName: "Tom S.",
    rating: 4.4,
    comment: "Laura handled my music contract negotiation well. Good service!",
    date: "2025-01-10",
    lawyerId: "15",
  },
  {
    id: "16",
    clientName: "Julia O.",
    rating: 4.8,
    comment: "Matthew resolved my maritime dispute quickly. Very experienced!",
    date: "2025-02-15",
    lawyerId: "16",
  },
  {
    id: "17",
    clientName: "Kevin W.",
    rating: 4.7,
    comment: "Nicole protected my data privacy effectively. Great lawyer!",
    date: "2025-03-20",
    lawyerId: "17",
  },
  {
    id: "18",
    clientName: "Helen L.",
    rating: 4.5,
    comment: "Brian supported my education law case. Very dedicated!",
    date: "2025-04-05",
    lawyerId: "18",
  },
  {
    id: "19",
    clientName: "Chris N.",
    rating: 4.8,
    comment: "Kelly resolved my construction dispute efficiently. Excellent!",
    date: "2025-05-12",
    lawyerId: "19",
  },
  {
    id: "20",
    clientName: "Megan C.",
    rating: 4.6,
    comment:
      "Andrew handled my sports contract with expertise. Great experience!",
    date: "2025-06-18",
    lawyerId: "20",
  },
];

export const testimonials = [
  {
    name: "Jennifer Martinez",
    role: "Small Business Owner",
    content:
      "Found the perfect lawyer for my business needs. The platform made it so easy to compare and connect.",
    rating: 5,
    image:
      "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?q=80&w=580&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    name: "Robert Chen",
    role: "Individual Client",
    content:
      "Excellent service! The lawyer I found was professional, knowledgeable, and got great results.",
    rating: 5,
    image:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
  },
  {
    name: "Lisa Thompson",
    role: "Family Law Client",
    content:
      "The verification process gave me confidence. My lawyer was exactly what I needed during a difficult time.",
    rating: 5,
    image:
      "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
  },
];

export const dashboardData = {
  upcomingBookings: [
    {
      id: "1",
      clientId: "client1",
      lawyerId: "lawyer1",
      date: "2025-08-05",
      time: "10:00",
      duration: 60,
      status: "confirmed",
      type: "consultation",
      notes: "Initial consultation for divorce proceedings",
      meetingLink: "https://meet.example.com/room1",
      totalAmount: 200,
      paymentStatus: "paid",
      createdAt: "2025-08-01T10:00:00Z",
    },
    {
      id: "2",
      clientId: "client1",
      lawyerId: "lawyer2",
      date: "2025-08-08",
      time: "14:00",
      duration: 90,
      status: "pending",
      type: "meeting",
      notes: "Contract review meeting",
      totalAmount: 300,
      paymentStatus: "pending",
      createdAt: "2025-08-02T09:00:00Z",
    },
  ],
  pastBookings: [
    {
      id: "3",
      clientId: "client1",
      lawyerId: "lawyer1",
      date: "2025-07-28",
      time: "15:00",
      duration: 60,
      status: "completed",
      type: "consultation",
      notes: "Legal advice consultation",
      totalAmount: 200,
      paymentStatus: "paid",
      createdAt: "2025-07-25T10:00:00Z",
    },
  ],
  totalSpent: 500,
  favoriteLaywers: [
    {
      id: "lawyer1",
      name: "Sarah Johnson",
      title: "Family Law Attorney",
      image: "user.png",
      rating: 4.9,
      reviewCount: 127,
      experience: 12,
      location: "New York, NY",
      practiceAreas: ["Family Law", "Divorce"],
      bio: "Experienced family law attorney",
      education: ["Harvard Law School"],
      languages: ["English", "Spanish"],
      hourlyRate: 200,
      availability: "Available",
      verified: true,
    },
  ],
  recentPayments: [
    {
      id: "pay1",
      bookingId: "1",
      clientId: "client1",
      lawyerId: "lawyer1",
      amount: 200,
      platformFee: 30,
      lawyerEarnings: 170,
      status: "completed",
      paymentMethod: "card",
      transactionId: "txn_123",
      createdAt: "2025-08-01T10:00:00Z",
      completedAt: "2025-08-01T10:01:00Z",
    },
  ],
};
